### ISSUE TITLE
String should use placeholders for "Download" post type name

### ISSUE THREAD

**Issue by dimadin** [easydigitaldownloads/edd-purchase-gravatars#13]
There are a few strings that use placeholder for `edd_get_label_singular()` value. There is no reason for that and actual name should be used in a string.

**Comment by ashleyfae** [comment]
I believe that's used because it can be filtered. For example, some people change "download" (the default) to "product".

**Comment by dimadin** [comment]
I just checked EDD core and see that you use this approach all the time, I wasn't aware of that before. However, as someone that translate WordPress for 14 years, I can tell you that this is wrong. It not that simple in languages other than English.  Placeholders should be used when value is really dynamic. This is not dynamic, value is predictable, filtered value is an exception. Take a look at [`get_post_type_labels()`](https://developer.wordpress.org/reference/functions/get_post_type_labels/) for example, there is a reason why 30 different strings are used just when registering post type.

Since this requires completely different approach in EDD core, I am closing issue for now.

**Comment by ashleyfae** [comment]
Thanks for your feedback. :+1:
