### ISSUE TITLE
Update plugin information

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-purchase-gravatars#4]
- [ ] Update Plugin URI: `https://easydigitaldownloads.com/downloads/edd-purchase-gravatars/`
- [ ] Update Author: `Easy Digital Downloads`
- [ ] Update Author URI: `https://easydigitaldownloads.com`
- [ ] Update readme.txt contributors: `easydigitaldownloads, sumobi`

Check off the list once completed: https://trello.com/c/XWLBRC2o/275-update-authorship-of-edd-plugins

**Comment by cklosowski** [comment]
This was done already, removing from milestone and closing.
