### ISSUE TITLE
Update for PHP Standards

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-purchase-gravatars#5]
```
Methods with the same name as their class will not be constructors in a future version of PHP; EDD_Purchase_Gravatars_Widget has a deprecated constructor	
```

`wp-content/plugins/edd-purchase-gravatars/edd-purchase-gravatars.php:434`

**Comment by brashrebel** [comment]
This is now throwing errors for customers: https://secure.helpscout.net/conversation/450059683/68593?folderId=180499

**Comment by brashrebel** [comment]
Confirmed fixed! 🎉
